// Generates icons/<name>.svg (one file per icon) and
// icons/loroco-icons.svg (a <symbol> sprite for vanilla-HTML consumers)
// from icons/icons.json. Run via `pnpm build:icons`.
import { readFileSync, writeFileSync, readdirSync, unlinkSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const iconsDir = join(root, "icons");
const { icons } = JSON.parse(readFileSync(join(iconsDir, "icons.json"), "utf8"));

const SVG_ATTRS =
  'xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" ' +
  'stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"';

// Clear previously generated SVGs so renamed icons don't leave strays.
for (const f of readdirSync(iconsDir)) {
  if (f.endsWith(".svg")) unlinkSync(join(iconsDir, f));
}

const symbols = [];
for (const [name, elements] of Object.entries(icons)) {
  const body = elements.join("");
  writeFileSync(join(iconsDir, `${name}.svg`), `<svg ${SVG_ATTRS}>${body}</svg>\n`);
  symbols.push(`<symbol id="${name}" viewBox="0 0 24 24">${body}</symbol>`);
}

const sprite =
  `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" ` +
  `stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" style="display:none">` +
  symbols.join("") +
  `</svg>\n`;
writeFileSync(join(iconsDir, "loroco-icons.svg"), sprite);

// Plain-script copy for the demo page so it works from file:// too.
writeFileSync(
  join(root, "demo", "icons-data.js"),
  `// Generated by scripts/build-icons.mjs — do not edit.\nwindow.LOROCO_ICONS = ${JSON.stringify(icons)};\n`,
);

console.log(`Generated ${Object.keys(icons).length} icons + sprite in icons/`);
